version: '3.5'
services:
  server:
    container_name: api
    build:
      context: ./app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    build:
      context: ./mysql
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
